spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crm
    username: postgres
    password: q
  jpa:
    hibernate:
      ddl-auto: update

application:
  jwt:
    secret-key: longAndSecure longAndSecure longAndSecure longAndSecure longAndSecure longAndSecure
    token-prefix: "Bearer "
    expiration-after-days: 14
